[package]
name = "msgsrv-client"
version = "0.1.0"
edition = "2021"
rust-version = "1.75"
license = "MIT"
description = "Rust client for msgsrvd"

[dependencies]
tokio = { version = "1", features = ["net", "io-util", "sync", "time", "rt", "macros"] }
tracing = "0.1"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
tempfile = "3"
